### ISSUE TITLE
share buttons

### ISSUE THREAD

**Issue by rocchettomarco** [v-research/knowledgezero#7]
![image](https://user-images.githubusercontent.com/14936492/105480862-95a6df80-5ca6-11eb-835c-acd4d45d73fe.png)

add share via whatsapp, telegram and the like

**Comment by rhaidiz** [comment]
WhatsApp share button added by commit 8045227bfcf26c42befcd18333ea3e388f084eb1
Telegram share button added by commit 82c373f65c99d6f396e6b67e9c09e518b654926a

Should we add something else?
